apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-southeast-1

vpc:
  id: vpc-0650d799d878deb7e
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-06316ab81a5df7dea
      my-new-stack-PublicSubnet02:
        id: subnet-0681d34a91e66f8e1
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-04ae9ad4cf59383db
      my-new-stack-PrivateSubnet02:
        id: subnet-03e21fdf7aef07f6b

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
